/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRhythmRouteImport } from './routes/demo/rhythm'
import { Route as DemoPhoneRouteImport } from './routes/demo/phone'
import { Route as DemoKeyboardRouteImport } from './routes/demo/keyboard'
import { Route as DemoDateRouteImport } from './routes/demo/date'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRhythmRoute = DemoRhythmRouteImport.update({
  id: '/demo/rhythm',
  path: '/demo/rhythm',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPhoneRoute = DemoPhoneRouteImport.update({
  id: '/demo/phone',
  path: '/demo/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoKeyboardRoute = DemoKeyboardRouteImport.update({
  id: '/demo/keyboard',
  path: '/demo/keyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDateRoute = DemoDateRouteImport.update({
  id: '/demo/date',
  path: '/demo/date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/demo/date': typeof DemoDateRoute
  '/demo/keyboard': typeof DemoKeyboardRoute
  '/demo/phone': typeof DemoPhoneRoute
  '/demo/rhythm': typeof DemoRhythmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/demo/date': typeof DemoDateRoute
  '/demo/keyboard': typeof DemoKeyboardRoute
  '/demo/phone': typeof DemoPhoneRoute
  '/demo/rhythm': typeof DemoRhythmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/demo/date': typeof DemoDateRoute
  '/demo/keyboard': typeof DemoKeyboardRoute
  '/demo/phone': typeof DemoPhoneRoute
  '/demo/rhythm': typeof DemoRhythmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/demo/date'
    | '/demo/keyboard'
    | '/demo/phone'
    | '/demo/rhythm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/demo/date'
    | '/demo/keyboard'
    | '/demo/phone'
    | '/demo/rhythm'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/demo/date'
    | '/demo/keyboard'
    | '/demo/phone'
    | '/demo/rhythm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  DemoDateRoute: typeof DemoDateRoute
  DemoKeyboardRoute: typeof DemoKeyboardRoute
  DemoPhoneRoute: typeof DemoPhoneRoute
  DemoRhythmRoute: typeof DemoRhythmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/rhythm': {
      id: '/demo/rhythm'
      path: '/demo/rhythm'
      fullPath: '/demo/rhythm'
      preLoaderRoute: typeof DemoRhythmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/phone': {
      id: '/demo/phone'
      path: '/demo/phone'
      fullPath: '/demo/phone'
      preLoaderRoute: typeof DemoPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/keyboard': {
      id: '/demo/keyboard'
      path: '/demo/keyboard'
      fullPath: '/demo/keyboard'
      preLoaderRoute: typeof DemoKeyboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/date': {
      id: '/demo/date'
      path: '/demo/date'
      fullPath: '/demo/date'
      preLoaderRoute: typeof DemoDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DemoDateRoute: DemoDateRoute,
  DemoKeyboardRoute: DemoKeyboardRoute,
  DemoPhoneRoute: DemoPhoneRoute,
  DemoRhythmRoute: DemoRhythmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
