/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SineRouteImport } from './routes/sine'
import { Route as ScuffedRouteImport } from './routes/scuffed'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PhoneNumberRouteImport } from './routes/phoneNumber'
import { Route as MorseRouteImport } from './routes/morse'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'

const SineRoute = SineRouteImport.update({
  id: '/sine',
  path: '/sine',
  getParentRoute: () => rootRouteImport,
} as any)
const ScuffedRoute = ScuffedRouteImport.update({
  id: '/scuffed',
  path: '/scuffed',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneNumberRoute = PhoneNumberRouteImport.update({
  id: '/phoneNumber',
  path: '/phoneNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const MorseRoute = MorseRouteImport.update({
  id: '/morse',
  path: '/morse',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/morse': typeof MorseRoute
  '/phoneNumber': typeof PhoneNumberRoute
  '/register': typeof RegisterRoute
  '/scuffed': typeof ScuffedRoute
  '/sine': typeof SineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/morse': typeof MorseRoute
  '/phoneNumber': typeof PhoneNumberRoute
  '/register': typeof RegisterRoute
  '/scuffed': typeof ScuffedRoute
  '/sine': typeof SineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/morse': typeof MorseRoute
  '/phoneNumber': typeof PhoneNumberRoute
  '/register': typeof RegisterRoute
  '/scuffed': typeof ScuffedRoute
  '/sine': typeof SineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/morse'
    | '/phoneNumber'
    | '/register'
    | '/scuffed'
    | '/sine'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/morse'
    | '/phoneNumber'
    | '/register'
    | '/scuffed'
    | '/sine'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/morse'
    | '/phoneNumber'
    | '/register'
    | '/scuffed'
    | '/sine'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MorseRoute: typeof MorseRoute
  PhoneNumberRoute: typeof PhoneNumberRoute
  RegisterRoute: typeof RegisterRoute
  ScuffedRoute: typeof ScuffedRoute
  SineRoute: typeof SineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sine': {
      id: '/sine'
      path: '/sine'
      fullPath: '/sine'
      preLoaderRoute: typeof SineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scuffed': {
      id: '/scuffed'
      path: '/scuffed'
      fullPath: '/scuffed'
      preLoaderRoute: typeof ScuffedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phoneNumber': {
      id: '/phoneNumber'
      path: '/phoneNumber'
      fullPath: '/phoneNumber'
      preLoaderRoute: typeof PhoneNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/morse': {
      id: '/morse'
      path: '/morse'
      fullPath: '/morse'
      preLoaderRoute: typeof MorseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MorseRoute: MorseRoute,
  PhoneNumberRoute: PhoneNumberRoute,
  RegisterRoute: RegisterRoute,
  ScuffedRoute: ScuffedRoute,
  SineRoute: SineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
